-- AlterTable
ALTER TABLE "Analysis" ALTER COLUMN "q_attempted" SET DEFAULT 0,
ALTER COLUMN "q_correct" SET DEFAULT 0,
ALTER COLUMN "q_incorrect" SET DEFAULT 0,
ALTER COLUMN "op1" SET DEFAULT 0,
ALTER COLUMN "op2" SET DEFAULT 0,
ALTER COLUMN "op3" SET DEFAULT 0,
ALTER COLUMN "op4" SET DEFAULT 0;
